# Generated by Django 5.0.6 on 2024-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=250)),
                ('birth_date', models.DateField(null=True)),
                ('membership', models.CharField(choices=[('S', 'SILVER'), ('G', 'GOLD'), ('D', 'DIAMOND')], default='S', max_length=1)),
                ('points', models.IntegerField(default=50)),
            ],
            options={
                'ordering': ['First_name', 'Last_name'],
            },
        ),
    ]
