# Generated by Django 5.0.6 on 2024-06-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=45345, max_length=128),
            preserve_default=False,
        ),
    ]
